version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: x64
shallow_clone: true
clone_folder: c:\projects\winobjex64

build_script:
- cmd: msbuild Source\WinObjEx64.sln /m /verbosity:normal /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

artifacts:
- path: Source\WinObjEx64\output\x64\Release\bin\WinObjEx64.exe
  name: WinObjEx64
